steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && ./create_appyaml.sh && gcloud app deploy']
  env:
  - 'MONGO_USER=$_USER'
  - 'MONGO_PASSWORD=$_PASSWORD'
timeout: '1600s'

