services:
  backend:
    build:
      context: .
    ports:
      - "8080:3000"
      - "9229:9229"
    volumes:
      - "./src:/usr/src/app/src"
    environment:
      ENV: local
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
